[package]
name = "lotter-jug-actix-bin"
version = "0.1.0"
authors = ["fteychene <francois.teychene@gmail.com>"]

[dependencies]
failure = "0.1.3"
failure_derive = "0.1.2"
actix = "0.7"
actix-web = { version = "0.7", features = ["alpn"] }
tokio = "0.1.11"
serde = "1.0"
serde_derive = "1.0"
uuid = { version = "0.5", features = ["serde", "v4"] }
log = "0.4"
env_logger = "0.5.13"
diesel = { version = "^1.3.3", features = ["sqlite", "r2d2"] }
r2d2 = "0.8"
jug_actix_lottery = { path = "../lottery" }